### ISSUE TITLE
Modify OKS search paths to prioritize checked-out source repositories

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/daq-cmake#111]
OKS currently uses DUNEDAQ_SHARE_PATH to search for database files using the `oksconfig://` scheme. This variable is set during the install step to point to each package's installed share directory. However, when using tools such as `dbe_main`, this means that while you can point the editor to a single file from the sourcecode area, any included files are brought in from the install directory. Any changes made to those included files will then be lost on future calls to the "install" build step unless the user manually copies them back to the source.

An obvious hack is to prepend the source directories to DUNEDAQ_SHARE_PATH when working with the config editor, but it might be a good idea to have a more comprehensive solution in place so that user frustration is minimized.

**Comment by eflumerf** [comment]
I wonder if it would be suitable to have OKS mark files loaded from "build", "install" or "cvmfs" directories as read-only...

**Comment by jcfreeman2** [comment]
After doing some testing/code review of the OKS repos yesterday, it appears that removing write permissions from included OKS files makes no difference to `dbe` and that it's _still_ possible to edit them. We can consider whether it's worth filing an Issue in `dbe` and/or `oks` and fixing this, but in the meantime I think the solution to use is to have `dbe` use a different environment variable other than `DUNEDAQ_SHARE_PATH` which prioritizes schema files in checked-out repos rather than in installation directories. So I'll close this Issue and reopen a new one in `dbe`.
