### ISSUE TITLE
Automatic rebuild after schema.jsonnet file is changed

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-cmake#12]
I've noticed that when I edit a *schema.jsonnet file in the /schema subdirectory of a project (e.g. [dfmodules/schema/dfmodules-HDF5DataStore-schema.jsonnet](https://github.com/DUNE-DAQ/dfmodules/blob/8f92ffbacda574738049c4a23412b4b65d605284/schema/dfmodules-HDF5DataStore-schema.jsonnet)) and then re-run the build using the `build_daq_software.sh` command, the build system does not seem to notice that the *schema.jsonnet has been changed, and it does not re-recreate the generated Nljs.jpp and Structs.hpp files unless I add the "--clean' option to `build_daq_software.sh`.

In the CMakeLists.txt file of the package all that I did to enable the code generation was to add the "SCHEMA" directive to the appropriate line, as seen [here](https://github.com/DUNE-DAQ/dfmodules/blob/8f92ffbacda574738049c4a23412b4b65d605284/CMakeLists.txt#L18).

Is there something extra that I need to do?
Thanks,
Kurt

**Comment by jcfreeman2** [comment]
@bieryAtFnal @alessandrothea This is going to require some thought. The auto-generation of the header files occurs during cmake's config+generate phases when the code in `daq_add_plugin` is run, and not during its build phase. However, as described in https://github.com/DUNE-DAQ/daq-buildtools/issues/18, in order to speed up the execution time of `build_daq_software.sh` the config+generate phase is only run during a clean build (or more properly, if `./build/CMakeCache.txt` isn't found). To accomplish what's described in this Issue while still preserving speed it may be necessary to add a function to `moo.cmake` which, instead of actually executing a moo command (which is what happens in `moo_codegen`), will instead return a string representing the command. That command can then be automatically executed whenever the schema file is touched.

**Comment by jcfreeman2** [comment]
Quick update:
* I've got daq-cmake to solve this issue in a formal sense, but I haven't yet convinced myself that the code doesn't do more work than it needs to (though it might turn out to be fine)
* I replaced jcfreeman2/issue12_schema_change_rebuilds_plugin with jcfreeman2/issue12_schema_change_rebuilds_plugin_v2 since the former was based off of the dunedaq-v2.0.0 tag of daq-cmake rather than the develop branch

**Comment by jcfreeman2** [comment]
Handled through PR #19
