### ISSUE TITLE
Reduce developers' direct interaction with moo

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-cmake#27]
As covered in Issue #12, the build system currently can be told to associate a schema file with a plugin, using moo to generate headers and rebuilding the plugin whenever the schema file is changed. However, it's still the case that:

* Only schema files directly associated with plugins are used to generate headers. For schema files which aren't directly associated with plugins, developers need to manually create them (see, e.g.,  https://github.com/DUNE-DAQ/timing/blob/87fee7f77aabdb9093b812f64ef5c481616c9532/schema/generate.sh)
* If a piece of code besides the plugin code needs to use a plugin's generated headers, developers need to remember to call `add_dependencies` linking the piece of code to the plugin. This is error prone and clutters up the CMakeLists.txt file, see bug Issue DUNE-DAQ/ipm#15 for an example.

It would nice if developers didn't need to worry about the two points above. One solution would be for the build system to generate headers off of _all_ `*schema.jsonnet` files, not just those associated with plugins, and to do this before attempting to compile any C++ code so that the problem of missing generated headers won't arise.

**Comment by alessandrothea** [comment]
I may need to get back to this with a fresher mind, as it is quite late here in Europe, but let me leave here some initial thoughts. The issues listed above, which popped up in the last few days due to developers making more and more use of code generation, are symptomatic of the currently limited moo/cmake integration being stretched to cover cases which was not supposed to cover. I believe that solving these issues requires taking a step back at the full picture. There are 2 main aspects to consider:
1. The relationship between schema file and consumer. What cases need to be supported
2. What parameters need to be provided to moo in each.

Starting from 1. this is what I have 
   - "Private" plugin schema. This is the only case currently supported. The schema only serves the plugin. The generated header is considered "private" and generated in `src/`, with other static headers. NOTE: unittests *may* need to have access to the generated headers.
   - "Shared" plugin schema. The schema is shared by multiple plugins in the same package. Example in ipm where a sender/receiver test plugins pair uses the same command data. Both consumers of the schema depend on the codegen being run before they are compiled.
   - "Public" library schema. the generated headers are part of the public package interface and/or used by the main library. The main library depends on the codegen target.
   - "Interface" schema: Similar to the previous case, but there may not be any library or static header in the package. Unlikely but possible case.

2. This requires more time, but it is worth remembering that moo requires the following parameters along with the schema file
   - path
   - ctxpath
   - model file
   - template
The default values set in the plugin case need to be checked against the others. Note that model file and template are taken from moo but are likely to be needed in the future.

I need to stop here now. To be continued...
